#!/bin/bash

# Ubuntu 20.04 provides mvn version 3.6.3, which is not compatible with Java 17 it seems.
# Install the wrapper with:
#
#   JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ mvn wrapper:wrapper


JAVA_HOME=~/.jdks/openjdk-17.0.2/ ./mvnw compile exec:java
